CREATE TABLE billionshop.BSSDEMO (
	DEMODEMOID      NUMERIC(4) NOT NULL,
	DEMOTESTDATA1   VARCHAR(255) NULL,
	DEMOTESTDATA2   VARCHAR(255) NULL,
	DEMOCREDAT      TIMESTAMP NOT NULL,
	DEMOCREUSR		VARCHAR(150) NOT NULL,
	DEMOUPDDAT      TIMESTAMP NOT NULL,
	DEMOUPDUSR		VARCHAR(150) NOT NULL
	CONSTRAINT bssdemo_pk PRIMARY KEY (demodemoid)
)
-- Column comments

COMMENT ON COLUMN billionshopdb.BSSDEMO.DEMODEMOID IS 'Demo Id';
COMMENT ON COLUMN billionshopdb.BSSDEMO.DEMOTESTDATA1 IS 'demotest data1';
COMMENT ON COLUMN billionshopdb.BSSDEMO.DEMOTESTDATA2 IS 'demotest data2';
COMMENT ON COLUMN billionshopdb.BSSDEMO.DEMOCREDAT IS 'Creation Date';
COMMENT ON COLUMN billionshopdb.BSSDEMO.DEMOCREUSR IS 'Creation User';
COMMENT ON COLUMN billionshopdb.BSSDEMO.DEMOUPDDAT IS 'Last Update Date';
COMMENT ON COLUMN billionshopdb.BSSDEMO.DEMOUPDUSR IS 'Last Update User';